### ISSUE TITLE
Specifying container for webgl canvas

### ISSUE THREAD

**Issue by melchiorb** [agargaro/three.ez#53]
Hello,

this is an awesome project that's adding a lot of the missing things in three.js!

Is there a way to create the canvas inside another html element (I did not find one).

And if not, is this planned sometime or is there a good workaround?

Thanks!

**Comment by agargaro** [comment]
Hello!

When you instantiate the `Main`, you can set the WebGLRenderer parameters:

`const main = new Main({ rendererParameters: { canvas: document.getElementById('yourCanvasId') });`

do you mean this?

**Comment by melchiorb** [comment]
Perfect, that solves it (I found the `fullscreen` flag, but missed `rendererParameters`).

Thanks!
