### ISSUE TITLE
How to use it with an existing project, I mean, I already have a lot of code in my project, and now I just want to use the events feature to join my project without having to change the scene, camera, renderer, etc. settings in the existing project

### ISSUE THREAD

**Issue by WREQI** [agargaro/three.ez#75]
How to use it with an existing project, I mean, I already have a lot of code in my project, and now I just want to use the events feature to join my project without having to change the scene, camera, renderer, etc. settings in the existing project

**Comment by agargaro** [comment]
I was already planning to modularize everything into several packages (already started with InstancedMesh2).

If you only need the event package I could make it available soon :)

**Comment by WREQI** [comment]
> 我已经计划将所有内容模块化为几个包（已经从 InstancedMesh2 开始）。
> 
> 如果您只需要活动包，我可以尽快提供:)
> 
> 如果您有兴趣，我们可以在 Discord 上私下交谈，这样我们就可以加快流程。

Thank you very much, but we have a very big time difference, I'm here in China at 9 a.m., and you're at 2 a.m

**Comment by WREQI** [comment]
https://github.com/mrdoob/three.js/issues/15965  Maybe you can add a custom hub axis to three.ez, and after setting the hub point, it is correct to use Box3Helper and transformControls? It will make it easier to develop directly with three.js and specify the rotation of the point. Also three.js addition of this feature is a long way off. @agargaro

**Comment by agargaro** [comment]
For the pivot you can try using it like this, as described in the bug. 

[https://stackblitz.com/edit/three-ez-box-and-draggable-pivot?file=src%2Fmain.ts](https://stackblitz.com/edit/three-ez-box-and-draggable-pivot?file=src%2Fmain.ts)

But the transform controls (and other components) doesn't work... it would need some modification. I don't think it will be possible to put it in the package soon for now

**Comment by WREQI** [comment]
Thank you for your answer　　https://stackblitz.com/edit/three-ez-box-and-draggable-pivot-t9cfbd?file=src%2Fmain.ts　　　I added TransformControls to your case and it doesn't display correctly　　TransformControls ? @agargaro

**Comment by WREQI** [comment]
![image](https://github.com/agargaro/three.ez/assets/35467304/e94b59a8-9be0-46a8-90db-22db68512ce0)

**Comment by agargaro** [comment]
There is a conflict with a property named "dragging" of transformControls, because my library also uses it. 

Since it's a very important component I guess I'll have to change the name of my property to 'isDragging' or something that doesn't create a conflict.

I'll do it asap :)

**Comment by WREQI** [comment]
![image](https://github.com/agargaro/three.ez/assets/35467304/8752df9e-c200-4bb3-8cdd-92725a95082d)
@agargaro This is displayed incorrectly，TransformControls, with no pivot point set for the object,How to fix it?  https://stackblitz.com/edit/three-ez-box-and-draggable-pivot-kmiduc?file=src%2Fmain.ts

**Comment by agargaro** [comment]
Mmm...

I converted the official `TransformControls` example.

official: [https://threejs.org/examples/misc_controls_transform.html](https://threejs.org/examples/misc_controls_transform.html)

converted: [https://stackblitz.com/edit/three-ez-transformcontrols?file=src%2Fmain.ts](https://stackblitz.com/edit/three-ez-transformcontrols?file=src%2Fmain.ts)

Can you check if you still notice anything that is not working?

**Comment by WREQI** [comment]
![微信截图_20240315161213](https://github.com/agargaro/three.ez/assets/35467304/0aa8951a-53d9-40a6-885f-785dc862a529)
https://stackblitz.com/edit/three-ez-transformcontrols-1h48ro?file=src%2Fmain.ts @agargaro

**Comment by agargaro** [comment]
The transformControls should be modified to support pivot point...

Are you able to modify it? I could try but I am currently working on something else and don't have much time

**Comment by WREQI** [comment]
I tried for hours and it didn't work @agargaro

**Comment by agargaro** [comment]
I'll finish the event package first and then take a look. Probably next week

**Comment by melchiorb** [comment]
+1 for modularized packages 😀

Being able to use the prts you need in existing code would make this project even more useful and probably boost adoption a lot.

If the events system were available stand alone, I'd replace my homemade system immediately.

Thanks @agargaro for being so responsive to this topic!

**Comment by agargaro** [comment]
@melchiorb I have almost finished the package but I need some help to test a real use case. Can we talk on discord? :)

**Comment by agargaro** [comment]
@WREQI 
@melchiorb 

I have published the package: [https://www.npmjs.com/package/@three.ez/interaction?activeTab=readme](https://www.npmjs.com/package/@three.ez/interaction?activeTab=readme)

Example with three.js vanilla: [https://stackblitz.com/edit/three-ez-interaction-template-vanilla?file=package.json](https://stackblitz.com/edit/three-ez-interaction-template-vanilla?file=package.json)

I will write the full documentation shortly. 

If you try the package can you please give me feedback?

**Comment by WREQI** [comment]
> @WREQI @melchiorb
> 
> 我已经发布了软件包：https://www.npmjs.com/package/@three.ez/interaction?activeTab=readme
> 
> 香草three.js示例：https://stackblitz.com/edit/three-ez-interaction-template-vanilla?file=package.json
> 
> 事件列表文档：
> 
> * https://agargaro.github.io/three.ez/docs/api/interfaces/Events.MiscEvents
> * https://agargaro.github.io/three.ez/docs/api/interfaces/Events.InteractionEvents
> 
> 我将很快编写完整的文档。
> 
> 如果您尝试该软件包，请给我反馈吗？:)
I'll try to see if the change controller solves it over the weekend

**Comment by WREQI** [comment]
discord? Where is it?

**Comment by agargaro** [comment]
I saw that you logged into the server :) anyway if anyone else needs it, the link is in the repository readme
